[package]
name = "brainfuck"
authors = ["Tom-the-Bomb"]
description = "a brainfuck interpreter implemented in rust"
repository = "https://github.com/Tom-the-Bomb/brainfuck-rs"
license = "MIT"
readme = "README.md"
version = "0.1.0"
edition = "2021"
keywords = [
    "Programming language"
]
categories = [
    "Compilers"
]

[dependencies]