name: Rust linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest stable Rust toolchain with clippy
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        run: cargo build --release --all-features --verbose

      - name: Run tests
        run: cargo test --release --all-features --verbose -- --nocapture --test-threads 1

      - name: Run clippy
        run: cargo clippy --workspace --all-features -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo